class Config:
    BOOTSTRAP_SERVERS = "localhost:19092"
    SCHEMA_REGISTRY_URL = "http://localhost:18081"


    TOPIC_NAME_TRANSACTIONS = "transactions"
    TOPIC_NAME_ML_FEATURES_HISTORICAL = "ml_features_historical"
    TOPIC_NAME_ML_FEATURES_LIVE = "ml_features_live"

    SCHEMA_SUBJECT_TRANSACTIONS = f"{TOPIC_NAME_TRANSACTIONS}-value"
    SCHEMA_SUBJECT_ML_FEATURES_HISTORICAL = f"{TOPIC_NAME_ML_FEATURES_HISTORICAL}-value"
    SCHEMA_SUBJECT_ML_FEATURES_LIVE = f"{TOPIC_NAME_ML_FEATURES_LIVE}-value"


TOPICS_TO_SETUP = [
    Config.TOPIC_NAME_TRANSACTIONS,
    Config.TOPIC_NAME_ML_FEATURES_HISTORICAL,
    Config.TOPIC_NAME_ML_FEATURES_LIVE,
]

SCHEMA_TO_SETUP = [
    Config.SCHEMA_SUBJECT_TRANSACTIONS,
    Config.SCHEMA_SUBJECT_ML_FEATURES_HISTORICAL,
    Config.SCHEMA_SUBJECT_ML_FEATURES_LIVE,
]
